config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :packages do
    resources :cart_items, only: :create
  end

  resources :cart_items, only: :destroy

  resources :orders, only: [:create, :show, :index, :edit, :update] do
    resources :payments, only: [:new, :create]
      resources :restaurants


  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :restaurant, optional: true
  belongs_to :cart
  geocoded_by :address_start, latitude: :ltd_starts, longitude: :lng_starts
  validates :day, presence: true, on: :update_order
  validates :time_start, presence: true, on: :update_order
  validates :time_end, presence: true, on: :update_order
  validates :address_start, presence: true, on: :update_order
  after_validation :geocode, if: :will_save_change_to_address_start?
  after_validation :geocode_address_end, if: :will_save_change_to_address_end?
  # after_save :direction_json, if: :will_save_change_to_address_end? || :will_save_change_to_address_start?
  monetize :amount_cents

  def direction_json
    self.direction = JSON.parse(HTTP.get("https://api.mapbox.com/directions/v5/mapbox/walking/#{self.lng_starts},#{self.ltd_starts};#{self.lng_ends},#{self.ltd_ends}?steps=true&access_token=#{ENV['MAPBOX_API_KEY']}").body)
    self.save
  end
  private

  def geocode_address_end
    coordinates = Geocoder.search(address_end).first.coordinates
    self.ltd_ends = coordinates[0]
    self.lng_ends = coordinates[1]
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    @orders = Order.geocoded
    @markers = @orders.map do |ord|
      {
        lat: ord.latitude,
        lng: ord.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { ord: order }),
        image_url: helpers.asset_url('marker_icon.png')
      }
    end
  end

  def create
    # todo: implementer la methode order_params
    cart = Cart.find(params[:cart])
    @order = Order.new(cart: cart)
    sum = 0
    cart.cart_items.each do |a|
      sum += a.package.price * a.quantity
    end
    @order.amount = sum
    if @order.save
      redirect_to edit_order_path(@order)
    else
      render 'edit'
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.restaurant = Restaurant.first
    @order.address_end = Restaurant.first.address
      if @order.update(order_params) && @order.valid?(:update_order)
      redirect_to new_order_payment_path(@order)
      else
        render :edit
    end
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def edit
    @order = Order.find(params[:id])
    @restaurants = Restaurant.geocoded
    # modif le center une fois le migrate de usr generate.
    @center = [2.3800903, 48.864922]
    @markers = @restaurants.map do |restaurant|
    {
      lat: restaurant.latitude,
      lng: restaurant.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant })
    }
    end
  end

  private

  def order_params
    params.require(:order).permit(:status, :day, :time_start, :time_end, :address_start)
 end
end

app/views/orders/_info_window.html.erb
<div container ><i class="fas fa-seedling fa-2x" style="color: #82AE46"></i>
  <h5><strong>Vous êtes ici :</strong></h5>
</div>

app/views/orders/edit.html.erb
<div class="banner2" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('<%= cl_image_path'vegetables_assort_meiitm.jpg', height: 600, width: 1200, crop: :fill %>')">
  <!-- Tableau -->
  <h2 class = "mb-5 text-center"> Récapitulatif de commande </h2>
  <div id= tableau-recap class="container">
  <div>
    <table class="table table text-center" id="table-modal-shopping-basket">
      <thead>
        <th scope="col">Nom du panier</th>
        <th scope="col">Quantité</th>
        <th scope="col">Prix unitaire</th>
         <th scope="col">Total</th>
    </thead>
    <% total_price = 0 %>
    <% current_user.cart.cart_items.each do |cart_itemem| %>
      <tbody>
        <tr data-cart-item-id="<%= cart_itemem.id %>">
           <td><%= cart_itemem.package.name %></td>
           <td><%= cart_itemem.quantity  %></td>
           <td><%= cart_itemem.package.price %> €</td>
            <% price_per_panier = cart_itemem.package.price * cart_itemem.quantity %>
           <td><%= price_per_panier %> €</td>
           <td><%= link_to cart_item_path(cart_itemem), method: :delete, remote: true do %>
              <i class="fa fa-trash destroy_package_cart_item"></i></td>
              <% end %>
         </tr>
         <% total_price += price_per_panier %>
      </tbody>
    <% end %>
  </table>
 </div>

            </div>
            <!-- Ici c'est le form -->
            <br>
            <br>
  <h2 class = "mb-5 text-center"> Quand souhaitez-vous récupérer votre commande ? </h2>
  <div class="container">
    <div class="form-wrapper" id= "form" id= "order_address_start">
      <%= simple_form_for @order, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>


        <%= f.input :day, as: :string, placeholder: "Choisir une date", label: "Quel jour récupèrerez-vous votre commande ?", required: true, input_html: {class: "datepicker"} %>
        <%= f.input :time_start, as: :string, placeholder: "De : 15h00", label: "A partir de quelle heure ?", required: true, input_html: {class: "timepicker"}, wrapper_html: {class: "schedule-input ml-1"} %>
        <%= f.input :time_end, as: :string, placeholder: "A : 17h00", label: "Jusqu'à quelle heure ?", required: true, input_html: {class: "timepicker"}, wrapper_html: {class: "schedule-input ml-1 mr-1"} %>
        <%= f.input :address_start, as: :string, label: "Quelle est votre adresse ?", required: true, placeholder: "16 villa gaudelet" %>
        <%= f.button :submit, "Valider", class: "btn btn-lg btn-flat-home ml-2" %>
      <% end %>
    </div>
  </div>
          </div>
        </div>
      </div>
<!-- End Modal de Cart -->
</div>

app/views/orders/show.html.erb
  <div class="jumbotron text-center" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.7)), url('<%= cl_image_path'veggi_lt3fr1.jpg', height: 300, width: 1200, crop: :fill %>'); color:white">
    </div>

<div class="container mt-2">
  <div class="row justify-content-center" >
    <div class="col-md-8 mt-2" >
    <%= form_tag order_payments_path(@order) do %>
      <h3 class ="mb-4" style="color:#82AE46">Détails de la commande: </h3>
      <div class="container">
        <table id="dash" class="table table-hover">
          <thead>
            <tr>
              <th style="width:80%"><h5><strong>Produits </strong></h5></th>
              <th style="width:20%"><h5><strong>Prix</strong></h5></th>
              <th style="width:11%"><h5><strong>Statut</strong></h5></th>
            </tr>
          </thead>
          <tbody>
          <% current_user.cart.cart_items.each do |item| %>
            <tr>
              <td data-th="Product">
                <div class="row">
                  <div class="col-sm-3 hidden-xs"><%= cl_image_tag item.package.photo, width: 250 %></div>
                  <div class="col-sm-8 ml-3">

                    <p class="commande"><strong> <%= item.package.name%></strong> </p>
                    <p class="commande"><%= item.package.description%></p>
                    <p class="commande"> Livrasion: le <strong><%= @order.day.strftime("%-d %B %Y") %><br></strong> entre <strong><%= @order.time_start.strftime("%H:%M") %> et <%= @order.time_end.strftime("%H:%M") %></strong> à <strong><%= @order.address_end%></strong></p>

                  </div>
                </div>
              </td>
              <td data-th="Price">
                <div class="mt-5">
                <%= item.package.price %> € x <%=item.quantity %>
                </div>
              </td>
              <td data-th="Price">
                <div class="mt-5"><strong style="color: #128EE4; text-transform: capitalize; border:1px solid #128EE4; padding: 0.25rem 0.5rem; border-radius:2px; "><%= @order.status %></strong>

                </div>
              </td>
            </tr>
          <% end %>
          </tbody>
          <tfoot>
            <tr><td ></td>
              <td class="hidden-xs"><strong>TOTAL: <%= humanized_money_with_symbol(@order.amount) %></strong></td></tr>
                        <p class="inline "><ins><%= link_to "Retour", dashboard_path %></ins>
          </p>
          </tfoot>
<tr></tr>
        </table>

      </div>
    <% end %>

</div>
</div>