config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :packages do
    resources :cart_items, only: :create
  end

  resources :cart_items, only: :destroy

  resources :orders, only: [:create, :show, :index, :edit, :update] do
    resources :payments, only: [:new, :create]
      resources :restaurants


  end

end

app/views/pages/dashboard.html.erb
<div id="banner-index-packages" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('<%= cl_image_path'http://res.cloudinary.com/dhf3phkaa/image/upload/v1567155701/jjedbku3hfd6vgwyc4ah.jpg', height: 800, width: 1200, crop: :fill %>')">
    <h2 class="text-center" id="title-index-packages">Vos Achats</h2>
  </div>
<div class="container mt-2">

    <div class="row justify-content-center" >

      <div class="col-md-8 mt-2" >

        <table id="dash" class="table table-hover">
          <thead>
            <tr>
              <th style="width:90%"><h5><strong> Description </strong></h5></th>
              <th style="width:20%"><h5><strong>Prix</strong></h5></th>
              <th style="width:10%"><h5><strong>Statut</strong></h5></th>
            </tr>
          </thead>

          <% @myorders.each do |order| %>
          <%= form_tag order_payments_path(order) do %>
          <tbody>
            <tr>
              <td data-th="Product">
                <div class="row">
                  <div class="col-sm-3 hidden-xs"><%= cl_image_tag order.cart.cart_items.first.package.photo, width: 150 %></div>
                  <div class="col-sm-8 ml-3">
                    <p class="commande commande-number"><ins style="color: #82AE46"><strong style="color: #82AE46">Commande numéro : <%= order.id %></ins></strong></hp>
                    <p class="commande"> A récupérer le : <strong><%= l(order.day, format: '%d %B %Y', locale: 'fr') %><br></strong> Entre: <strong><%= order.time_start.strftime("%H:%M") %> et <%= order.time_end.strftime("%H:%M") %></strong> <br> A l'adresse: <br><strong><%= order.address_end%></strong></p>
                  </div>
                </div>
              </td>
              <td data-th="Price">
                <div class="mt-5">
                <strong><%= humanized_money_with_symbol(order.amount) %></strong>
                </div>
              </td>
              <td data-th="Price">
                <div class="mt-5", style="text-align: center"><strong style="color: #128EE4; text-transform: capitalize; border:1px solid #128EE4; padding: 0.25rem 0.5rem; border-radius:2px; "><%= order.status %></strong>
                <p class="inline btn btn-success btn-sm mt-3"><%= link_to "Détails", order_path(order) %></p>
              </td>
            </tr>
          </tbody>
          <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner div-text-carrousel">
    <div class="text-center text-carrousel">
      <h1><strong>Proxy Rungis</strong></h1>
      <br>
      <br>
       <br>
      <h4 class="mb-5"><strong >Des fruits et légumes de qualité, pas cher, juste en bas de chez vous!</strong></h4>

      <%= link_to packages_path do %>
        <div class="btn btn-lg btn-flat-home p-3">VOIR NOS PRODUITS</div>
      <% end %>
    </div>
    <div class="carousel-item active">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('<%= cl_image_path'vegetables_assort_meiitm.jpg', height: 600, width: 1200, crop: :fill %>')">
      </div>
    </div>
    <div class="carousel-item">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('<%= cl_image_path'ont5vs0mos0zbyhbkzi6.jpg', height: 600, width: 1200, crop: :fill %>')">

      </div>
    </div>
    <div class="carousel-item">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('<%= cl_image_path'sogf4wdf6efidnfa5cki.jpg', height: 600, width: 1200, crop: :fill %>')">
      </div>
    </div>
  </div>
</div>
<br>


 <div data-aos="fade-in">
<div class="container mt-5 mb-5" >
  <div class="row no-gutters ftco-services"; data-aos="fade-up">

    <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
      <div class="media block-6 services mb-md-0 mb-4">
        <div class="icon d-flex justify-content-center align-items-center mb-2"; style = "background:#E4B2D6">
          <i class='fas fa-truck fa-3x' style='color:white'></i>
        </div>
        <div class="media-body">
          <h3 class="heading mt-3">Livraison rapide</h3>
          <span>C'est le bon plan rapide et sans prise de tête!</span>
        </div>
      </div>
    </div>

    <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
      <div class="media block-6 services mb-md-0 mb-4">
        <div class="icon d-flex justify-content-center align-items-center mb-2"; style = "background: #FDAD75">
          <i class="fas fa-carrot fa-3x" style=' color:white'></i>
        </div>
        <div class="media-body">
          <h3 class="heading mt-3">Toujours frais</h3>
          <span>Manger des fruits et légumes frais n'a jamais été aussi simple!</span>
        </div>
      </div>
    </div>

    <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
      <div class="media block-6 services mb-md-0 mb-4">
         <div class="icon d-flex justify-content-center align-items-center mb-2"; style = "background: #A2D1E1">
          <i class="fas fa-seedling fa-3x" style="color: white"></i>
        </div>
        <div class="media-body">
          <h3 class="heading mt-3">Qualité supérieure</h3>
          <span>Des fruits et légumes de qualité, pas chers, juste en bas de chez vous!</span>
        </div>
      </div>
    </div>

    <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate fadeInUp ftco-animated">
      <div class="media block-6 services mb-md-0 mb-4">
        <div class="icon d-flex justify-content-center align-items-center mb-2"; style = "background: #A0CC78">
         <i class="fas fa-apple-alt fa-3x" style="color: white"></i>
        </div>
        <div class="media-body">
          <h3 class="heading mt-3">Écologique</h3>
          <span>Produits écologiques</span>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
<div class ="container mt-3 center">
  <br>
  <br>
  <br>
  <div data-aos="fade-in">
  <h4 style="text-transform: uppercase"><strong style="color: #82AE46"> Comment ça marche?</strong></h4>
  </div>
<br>
<div data-aos="fade-in">
<div class="container mt-5" >
  <div class="card-deck">

    <div class="card">
      <p class="card-title"> <span class="fa-stack fa-2x", style="color:#A0CC78";>
      <i class="fa fa-circle fa-stack-2x"></i>
      <strong class="fa-stack-1x text-white">1</strong>
      </span></p>
      <div class="d-flex justify-content-center" style="width:100% !important;">
        <div class="home-card-img">
          <%= cl_image_tag('vegetables_h6wfpy.png', width:300, height:300, crop: :fill, class: "image-icons")%>
        </div>
      </div>
      <h5 class="card-text mt-5"><strong>Vous choisissez </strong>votre panier de saison.</h5>
    </div>

    <div class="card">
      <p class="card-title"> <span class="fa-stack fa-2x", style="color:#A0CC78";>
      <i class="fa fa-circle fa-stack-2x"></i>
      <strong class="fa-stack-1x text-white">2</strong>
      </span></p>
      <div class="d-flex justify-content-center" style="width:100% !important;">
        <div class="home-card-img">
          <%= cl_image_tag('house_dgffe4.png', width:300, height:300, crop: :fill, class: "image-icons")%>
        </div>
      </div>
      <h5 class="card-text mt-5"><strong>Vous indiquez</strong> où vous habitez, et quand vous voulez récupérer le panier.</h5>
    </div>

    <div class="card">
      <p class="card-title"> <span class="fa-stack fa-2x", style="color:#A0CC78";>
      <i class="fa fa-circle fa-stack-2x"></i>
      <strong class="fa-stack-1x text-white">3</strong>
    </span></p>
      <div class="d-flex justify-content-center" style="width:100% !important;">
        <div class="home-card-img">
          <%= cl_image_tag('take-away_wkgpsr.jpg', width:300, height:300, crop: :fill, class: "image-icons")%>
        </div>
      </div>
      <h5 class="card-text mt-5"><strong> Vous récupérerez </strong> votre panier frais à l'endroit convenu.</h5>
    </div>
</div>
  </div>
</div>

  <br>
  <br>
  <br>
  <br>
  <br>

<div data-aos="fade-in">
  <h4 style="text-transform: uppercase"><strong style="color: #82AE46"> Nos valeurs: </strong></h4>

  </div>
  <br>
  <br>
<div data-aos="fade-in">
    <div class="container">
      <div class="row">

          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12" >

          <div class="box-part text-center"  style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5); height: 350px"><i class="fas fa-atom fa-3x mb-3" ; style="color: #82AE46"></i>

            <div class="title"><h4>Notre astuce</h4>
            </div>

            <div class="text px-3">
              <span>Grâce à une solution innovante et technologique, nous pouvons réduire les coûts et nous focaliser sur la qualité des aliments.</span>
            </div>

           </div>
        </div>

         <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

          <div class="box-part text-center" style=" box-shadow: 1px 2px 4px rgba(0, 0, 0, .5); height: 350px">

            <i class="fas fa-bullseye fa-3x mb-3"; style="color: #82AE46"></i>

            <div class="title">
              <h4>Notre mission</h4>
            </div>

            <div class="text px-3">
              <span>Notre mission, c'est de vous proposer des fruits et légumes toujours meilleurs, toujours moins chers et toujours plus proches de chez vous.</span>
             </div>
            </div>
        </div>

         <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">

          <div class="box-part text-center" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5); height: 350px">

             <i class="fab fa-leanpub fa-3x mb-3"; style="color: #82AE46"></i>

            <div class="title">
              <h4>Notre philosophie</h4>
            </div>

            <div class="text">
              <span>Nous travaillons avec les meilleurs producteurs de Rungis afin de vous proposer tous les jours des produits frais et de qualité à un prix raisonnable </span>
              <br>
              <br>
            </div>

           </div>
        </div>

        </div>

    </div>
</div>
  <br>
  <br>
  <br>
  <br>
  <div data-aos="fade-in">
  <h4 style="text-transform: uppercase"><strong style ="color: #82AE46"> Qui sommes-nous ?</strong></h4>
  </div>

  <br>
<div data-aos="fade-in">
  <div class ="container mt-5 mb-5">
    <!-- Grid row -->
  <div class="row">
    <!--Grid column-->
    <div class="col-lg-3 col-md-12 mb-lg-0 mb-4">
      <!--Card-->
      <div class="card testimonial-card" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
        <!--Background color-->
        <div class="card-up info-color card-person">
        <!--Avatar-->
      <div class="avatar-largee mx-auto white mt-2">
          <%= cl_image_tag("cricri_nrhylk.png", class: "rounded-circle img-fluid")%>


        </div>
      </div>
        <div class="card-body mt-3" style ="height: 230px">
          <!--Name-->
          <h5 class="font-weight-bold mb-4 text-center">Christophe B.</h5>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4" style="font-size: 13px"><i class="fa fa-quote-left pr-2"></i>Christophe va prochainement partir à l'étranger, pour un motif familial. Mis en disponibilité, il choisit de développer de nouvelles compétences avec Le Wagon.</p>
        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-3 col-md-12 mb-md-0 mb-4">
      <!--Card-->
      <div class="card testimonial-card" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
        <!--Background color-->
        <div class="card-up blue-gradient card-person">

        <!--Avatar-->
        <div class="avatar-largee mx-auto white mt-2">
          <%= cl_image_tag("goti_rz0xu6.png", class: "rounded-circle img-fluid")%>

        </div></div>
        <div class="card-body mt-3" style ="height: 230px">
          <!--Name-->
          <h5 class="font-weight-bold mb-4 text-center">  Gauthier H.</h5>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4"style="font-size: 13px"><i class="fa fa-quote-left pr-2"></i>Après plusieurs années dans la restauration, Gauthier a décidé de mettre ses connaissances au service de Proxy Rungis.</p>

        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-lg-3 col-md-12 mb-md-0 mb-5">
      <!--Card-->
      <div class="card testimonial-card" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
        <!--Background color-->
        <div class="card-up blue-gradient card-person">

        <!--Avatar-->
        <div class="avatar-largee mx-auto white mt-2">
          <%= cl_image_tag("cont_h8sgxz.png", class: "rounded-circle img-fluid")%>

        </div></div>
        <div class="card-body mt-3" style ="height: 230px">
          <!--Name-->
          <h5 class="font-weight-bold mb-4 text-center">Quentin D.</h5>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4"style="font-size: 13px"><i class="fa fa-quote-left pr-2"></i>Ancien commercial dans une grande multinationale, Quentin met à disposition son expertise afin d'obtenir les meilleurs accords avec les producteurs de Rungis. </p>
        </div>
      </div>
      <!--Card-->
    </div>
    <!--Grid column-->
    <div class="col-lg-3 col-md-12 mb-md-0 mb-4">
      <!--Card-->
      <div class="card testimonial-card" style="box-shadow: 1px 2px 4px rgba(0, 0, 0, .5)">
        <!--Background color-->
        <div class="card-up blue-gradient card-person">

        <!--Avatar-->
        <div class="avatar-largee mx-auto white mt-2">
          <%= cl_image_tag("ol_me3iho.png", class: "rounded-circle img-fluid")%>

        </div>
        </div>
        <div class="card-body mt-3" style ="height: 230px">
          <!--Name-->
          <h5 class="font-weight-bold mb-4 text-center">Olesya O.</h5>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4" style="font-size: 13px"><i class="fa fa-quote-left pr-2"></i>Anciennement ingénieure en Robotic, Olesya décide de quitter sa Suisse Natale afin de rejoindre Proxy Rungis en tant que dévellepeur fullstack.</p>
        </div>
      </div>
      <!--Card-->
    </div>
  </div>
   </div>
   </div>
   </div>


<br>
<br>
<br>